### ISSUE TITLE
How should the assets be organized here?

### ISSUE THREAD

**Issue by alexander-g** [poets-ai/elegy-assets#1]
Pushing large files directly into the repository is [restricted](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/conditions-for-large-files) by GitHub, so I guess this is not an option.
Shall I create a new release every time I want to upload assets? Any guidelines regarding the naming and organization?

**Comment by cgarciae** [comment]
My idea for this repo is that we just have releases here to upload stuff. I think we can just name the releases like this: `{asset_name}-{asset_version}`.
